/**
 * Generates supabase/seed.sql from the typed PLACEHOLDER content in src/content/*.
 * Run: npx tsx scripts/generate-seed.ts
 * Everything here is placeholder data (fictional people/companies) — replace before launch.
 */
import { writeFileSync } from "node:fs";
import { posts } from "../src/content/posts";
import { projectCategories, projects } from "../src/content/projects";
import { services } from "../src/content/services";
import { solutions } from "../src/content/solutions";
import { stats } from "../src/content/stats";
import { teamMembers } from "../src/content/team";
import { techLogos } from "../src/content/tech-logos";
import { testimonials } from "../src/content/testimonials";
import { blocksToDoc } from "../src/lib/rich";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) return v.length ? `array[${v.map(q).join(", ")}]::text[]` : "'{}'::text[]";
  if (typeof v === "object") return `${q(JSON.stringify(v))}::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const insert = (table: string, rows: Record<string, unknown>[]) => {
  if (!rows.length) return "";
  const cols = Object.keys(rows[0]);
  return `insert into public.${table} (${cols.join(", ")}) values\n${rows.map((r) => `  (${cols.map((c) => q(r[c])).join(", ")})`).join(",\n")};\n\n`;
};
const omit = <T extends Record<string, unknown>>(o: T, ...k: string[]) => Object.fromEntries(Object.entries(o).filter(([key]) => !k.includes(key)));

let sql = `-- =============================================================================
-- CODEX seed — PLACEHOLDER content (fictional clients/people). Generated by
-- scripts/generate-seed.ts from src/content/*. Do not edit by hand.
-- Triggers are disabled while seeding so the activity log starts clean.
-- =============================================================================
set session_replication_role = replica;

`;

// ------------------------------------------------------------------ dev users (local only)
const users = [
  ["00000000-0000-4000-a000-000000000001", "admin@codex.agency", "Youssef Nabil", "admin"],
  ["00000000-0000-4000-a000-000000000002", "editor@codex.agency", "Lina Farouk", "editor"],
  ["00000000-0000-4000-a000-000000000003", "viewer@codex.agency", "Karim Adel", "viewer"],
];
sql += "-- Local development accounts (password: codex-dev). NEVER seed these into production.\n";
for (const [id, email, name, role] of users) {
  sql += `insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-0000-0000-000000000000', '${id}', 'authenticated', 'authenticated', '${email}', extensions.crypt('codex-dev', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"],"role":"${role}"}', '{"full_name":"${name}"}', now(), now(), '', '', '', '');
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), '${id}', '${id}', '{"sub":"${id}","email":"${email}","email_verified":true}', 'email', now(), now(), now());
insert into public.profiles (id, email, full_name, role) values ('${id}', '${email}', '${name}', '${role}');\n`;
}
sql += "\n";

// ------------------------------------------------------------------ content
sql += insert("services", services.map((s) => omit(s, "id")));
sql += insert("solutions", solutions.map((s) => omit(s, "id")));
sql += insert("project_categories", projectCategories.map((c) => omit(c, "id")));
sql += insert(
  "projects",
  projects.map((p) => ({
    ...omit(p, "id", "content_en", "content_ar", "gallery", "seo_title_en", "seo_title_ar", "seo_description_en", "seo_description_ar"),
    content_en: null,
    content_ar: null,
  })),
);
sql += insert(
  "posts",
  posts.map((p) => ({ ...omit(p, "id"), content_en: blocksToDoc(p.content_en), content_ar: blocksToDoc(p.content_ar) })),
);
sql += insert("testimonials", testimonials.map((t) => omit(t, "id")));
sql += insert("team_members", teamMembers.map((t) => omit(t, "id")));
sql += insert("stats", stats.map((s) => omit(s, "id")));
sql += insert("tech_logos", techLogos.map((t) => omit(t, "id")));

sql += `insert into public.site_settings (id, email, phone, whatsapp, address_en, address_ar, socials, seo_title_en, seo_title_ar, seo_description_en, seo_description_ar, announcement_en, announcement_ar, announcement_href)
values (1, 'info@codexai.systems', '+20 120 780 9980, +20 102 902 0716', '201207809980,201029020716', 'Riyadh · Cairo · Dubai', 'الرياض · القاهرة · دبي',
  '{"instagram":"https://instagram.com/","linkedin":"https://linkedin.com/","behance":"https://behance.net/","x":"https://x.com/","tiktok":"https://tiktok.com/"}',
  'CODEX — Software, Branding & Marketing Agency', 'CODEX — وكالة برمجيات وهوية تجارية وتسويق',
  'CODEX is a digital agency with in-house development, brand and marketing teams.', 'CODEX وكالة رقمية بفرق داخلية للبرمجة والهوية والتسويق.',
  'New: AI agents for WhatsApp — book a free demo.', 'جديد: وكلاء ذكاء اصطناعي لواتساب — احجز عرضًا مجانيًا.', '/ai-automation');\n\n`;

// ------------------------------------------------------------------ sample leads (deterministic)
let seed = 20261006;
const r = () => ((seed = (seed * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff);
const pick = <T,>(a: readonly T[]) => a[Math.floor(r() * a.length)];
const FIRST = ["Ahmed", "Sara", "Omar", "Nour", "Khalid", "Mona", "Faisal", "Huda", "Tariq", "Reem", "Yousef", "Layla", "Hamad", "Dina", "Saeed", "Maha"];
const LAST = ["Hassan", "Al-Qahtani", "Mostafa", "Al-Mansoori", "Saleh", "Al-Sabah", "Ibrahim", "Al-Harthy", "Fathy", "Al-Otaibi", "Kamal", "Al-Balushi"];
const COMPANIES = ["Nakhla Dates", "Skyline Realty", "Fitbox", "Gulf Supply", "Maharat Academy", "Souq Box", "Bayt Coffee", null, null];
const MSG = [
  "We need a new Salla store with custom gifting and delivery slots.",
  "Looking for a WhatsApp AI agent to qualify real-estate leads.",
  "Rebrand for our coffee chain — logo, packaging and signage.",
  "Performance campaigns on Meta and TikTok for our clinic.",
  "نحتاج منصة تعليمية بالاشتراكات والشهادات.",
  "نرغب في أتمتة الطلبات بين شوبيفاي ونظام المحاسبة.",
];
const SERVICES = ["development", "branding", "marketing", "ai", "ecommerce", "other"] as const;
const BUDGETS = ["lt5k", "5to15k", "15to40k", "gt40k", "unsure"] as const;
const STATUSES = ["new", "new", "contacted", "contacted", "qualified", "proposal", "won", "lost"] as const;
const leads = Array.from({ length: 48 }, (_, i) => {
  const first = pick(FIRST);
  const last = pick(LAST);
  const status = i < 4 ? "new" : pick(STATUSES);
  const msg = pick(MSG);
  return {
    name: `${first} ${last}`,
    email: `${first.toLowerCase()}.${last.toLowerCase().replace(/[^a-z]/g, "")}${i}@example.com`,
    phone: `+9665${Math.floor(10000000 + r() * 89999999)}`,
    company: pick(COMPANIES),
    service: pick(SERVICES),
    budget: pick(BUDGETS),
    message: msg,
    locale: /[؀-ۿ]/.test(msg) ? "ar" : "en",
    country: pick(["SA", "SA", "EG", "AE", "KW", "OM"]),
    source_page: pick(["/contact", "/services", "/ai-automation", "/work"]),
    status,
    assigned_to: status === "new" ? null : pick([users[0][0], users[1][0]]),
    estimated_value: status === "new" ? null : Math.round((2000 + r() * 50000) / 500) * 500,
    position: i,
    created_at: new Date(Date.now() - Math.floor(Math.pow(r(), 1.4) * 90 * 864e5)).toISOString(),
  };
});
sql += "-- Sample leads (fictional)\n" + insert("leads", leads);
sql += `insert into public.lead_notes (lead_id, kind, body, created_at)
select id, 'created', 'Lead created from the website contact form.', created_at from public.leads;\n\n`;

// ------------------------------------------------------------------ 90 days of sample page views
sql += `-- Sample page views (synthetic) so analytics has history on day one
insert into public.page_views (path, locale, referrer, device, session_hash, created_at)
select (array['/', '/', '/', '/services', '/solutions', '/ai-automation', '/work', '/blog', '/about', '/contact'])[1 + floor(random() * 10)::int],
       case when random() < 0.6 then 'ar' else 'en' end,
       (array['google', 'google', 'direct', 'direct', 'instagram', 'linkedin', 'tiktok', 'chatgpt.com'])[1 + floor(random() * 8)::int],
       case when random() < 0.6 then 'mobile' when random() < 0.9 then 'desktop' else 'tablet' end,
       md5(d::text || (n % 140)::text),
       d + (random() * interval '23 hours')
  from generate_series(current_date - 89, current_date, interval '1 day') d
 cross join generate_series(1, 120 + floor(random() * 120)::int) n;

set session_replication_role = origin;
`;

writeFileSync("supabase/seed.sql", sql);
console.log(`seed.sql written (${(sql.length / 1024).toFixed(1)} KB)`);
